# Permalinks
permalink:           pretty

# Setup
title: 404. identity not found.
tagline: 정체성 없는 블로그
url: 'https://beoreoji.github.io'
paginate: 1
baseurl: ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Seonpil Kim
  url:               https://twitter.com/beoreoji
  email: swag.seonpil@email.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

plugins:
 - jekyll-paginate
 - jekyll-gist

analytics_id: UA-121641219-1
